{"name": "test_login_with_invalid_credentials_error[test@example.com-]", "status": "passed", "parameters": [{"name": "email", "value": "'test@example.com'"}, {"name": "password", "value": "''"}], "start": 1736196510127, "stop": 1736196510360, "uuid": "527d7014-5e79-4727-9615-9a880d5ad5ec", "historyId": "2efede98efcbebc2e0d81c43fc2e513a", "testCaseId": "6b9d0b2bbcc52e9a323a7a861fe1fa3b", "fullName": "tests.test_user_login.TestLoginUser#test_login_with_invalid_credentials_error", "labels": [{"name": "story", "value": "Логин с неверными данными"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Oxanas-MacBook-Pro.local"}, {"name": "thread", "value": "90867-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}